name: face_detection_ml_vision
description: Flutter plugin forked from brianmtully/flutter_google_ml_vision, using only face_detection
homepage: https://github.com/Mairramer/flutter_google_ml_vision
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.brianmtully.flutter.plugins.googlemlvision
        pluginClass: GoogleMlVisionPlugin
      ios:
        pluginClass: FLTGoogleMlVisionPlugin
